[package]
name = "git-graph"
version = "0.1.0"
authors = ["mlange-42 <martin_lange_@gmx.net>"]
edition = "2018"

[dependencies]
git2 = "0.13"
regex = "1.4"
itertools = "0.9"
svg = "0.8"
clap = "2.33"
lazy_static = "1.4"
term = "0.6"
term-painter = "0.3"
