[package]
name = "git-graph"
version = "0.1.4"
authors = ["Martin Lange <martin_lange_@gmx.net>"]
description = "Command line tool to show clear git graphs arranged for your branching model"
repository = "https://github.com/mlange-42/git-graph.git"
keywords = ["git", "graph"]
license = "MIT"
readme = "README.md"
edition = "2018"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
debug-assertions = false
overflow-checks = false

[dependencies]
git2 = "0.13"
regex = "1.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
itertools = "0.9"
svg = "0.8"
clap = "2.33"
lazy_static = "1.4"
yansi = "0.5"
atty = "0.2"
platform-dirs = "0.3"
crossterm = "0.19"
chrono = "0.4"
