[package]
name = "git-graph"
version = "0.1.1"
authors = ["mlange-42 <martin_lange_@gmx.net>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
debug-assertions = false
overflow-checks = false

[dependencies]
git2 = "0.13"
regex = "1.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
itertools = "0.9"
svg = "0.8"
clap = "2.33"
lazy_static = "1.4"
yansi = "0.5"
atty = "0.2"
platform-dirs = "0.3"
